[package]
name = "bevy_topdown_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.7.0"
image = "0.24.3"
serde = "1.0.139"
serde_json = "1.0.82"